# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='services.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eservices.proto\x12\x02pb\"\"\n\x0cSayHiRequest\x12\x12\n\nrequestMsg\x18\x01 \x01(\t\"\'\n\x10SayHelloResponse\x12\x13\n\x0bresponseMsg\x18\x01 \x01(\t\"%\n\x0eSayByeResponse\x12\x13\n\x0bresponseMsg\x18\x01 \x01(\t2F\n\x0fSayHelloService\x12\x33\n\x07\x43ompute\x12\x10.pb.SayHiRequest\x1a\x14.pb.SayHelloResponse\"\x00\x32\x42\n\rSayByeService\x12\x31\n\x07\x43ompute\x12\x10.pb.SayHiRequest\x1a\x12.pb.SayByeResponse\"\x00\x62\x06proto3')
)




_SAYHIREQUEST = _descriptor.Descriptor(
  name='SayHiRequest',
  full_name='pb.SayHiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestMsg', full_name='pb.SayHiRequest.requestMsg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=56,
)


_SAYHELLORESPONSE = _descriptor.Descriptor(
  name='SayHelloResponse',
  full_name='pb.SayHelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseMsg', full_name='pb.SayHelloResponse.responseMsg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=97,
)


_SAYBYERESPONSE = _descriptor.Descriptor(
  name='SayByeResponse',
  full_name='pb.SayByeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseMsg', full_name='pb.SayByeResponse.responseMsg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['SayHiRequest'] = _SAYHIREQUEST
DESCRIPTOR.message_types_by_name['SayHelloResponse'] = _SAYHELLORESPONSE
DESCRIPTOR.message_types_by_name['SayByeResponse'] = _SAYBYERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SayHiRequest = _reflection.GeneratedProtocolMessageType('SayHiRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAYHIREQUEST,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:pb.SayHiRequest)
  })
_sym_db.RegisterMessage(SayHiRequest)

SayHelloResponse = _reflection.GeneratedProtocolMessageType('SayHelloResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAYHELLORESPONSE,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:pb.SayHelloResponse)
  })
_sym_db.RegisterMessage(SayHelloResponse)

SayByeResponse = _reflection.GeneratedProtocolMessageType('SayByeResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAYBYERESPONSE,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:pb.SayByeResponse)
  })
_sym_db.RegisterMessage(SayByeResponse)



_SAYHELLOSERVICE = _descriptor.ServiceDescriptor(
  name='SayHelloService',
  full_name='pb.SayHelloService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=138,
  serialized_end=208,
  methods=[
  _descriptor.MethodDescriptor(
    name='Compute',
    full_name='pb.SayHelloService.Compute',
    index=0,
    containing_service=None,
    input_type=_SAYHIREQUEST,
    output_type=_SAYHELLORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAYHELLOSERVICE)

DESCRIPTOR.services_by_name['SayHelloService'] = _SAYHELLOSERVICE


_SAYBYESERVICE = _descriptor.ServiceDescriptor(
  name='SayByeService',
  full_name='pb.SayByeService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=210,
  serialized_end=276,
  methods=[
  _descriptor.MethodDescriptor(
    name='Compute',
    full_name='pb.SayByeService.Compute',
    index=0,
    containing_service=None,
    input_type=_SAYHIREQUEST,
    output_type=_SAYBYERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAYBYESERVICE)

DESCRIPTOR.services_by_name['SayByeService'] = _SAYBYESERVICE

# @@protoc_insertion_point(module_scope)
